version: "3"

services:
  postgres:
    image: "postgres:9.5"
    volumes:
      - postgres:/var/lib/postgresql/data

  chrome:
    image: selenium/standalone-chrome

  app:
    depends_on:
      - "postgres"
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/onebitexchange
      - gems:/gems
    links:
      - chrome

volumes:
  postgres:
  gems:
